Cadeia E
Cadeia ; Numero de aminoacidos da cadeia ; Numero de ligacoes dissulfidicas  : (a1,i5,i5)
E  333    0
Aminoacidos envolvidos nas ligacoes dissulfidicas  : n(i4,i4,/)
Sequencia de aminoacidos da cadeia A  : n(10(a5,1x),/)
VALI  LYS   GLU   PHE   LEU   ALA   LYS   ALA   LYS   GLU  
ASP   PHE   LEU   LYS   LYS   TRP   GLU   THR   PRO   SER  
GLN   ASN   THR   ALA   GLN   LEU   ASP   GLN   PHE   ASP  
ARG   ILE   LYS   THR   LEU   GLY   THR   GLY   SER   PHE  
GLY   ARG   VAL   MET   LEU   VAL   LYS   HIS   LYS   GLU  
SER   GLY   ASN   HIS   TYR   ALA   MET   LYS   ILE   LEU  
ASP   LYS   GLN   LYS   VAL   VAL   LYS   LEU   LYS   GLN  
ILE   GLU   HIS   THR   LEU   ASN   GLU   LYS   ARG   ILE  
LEU   GLN   ALA   VAL   ASN   PHE   PRO   PHE   LEU   VAL  
LYS   LEU   GLU   PHE   SER   PHE   LYS   ASP   ASN   SER  
ASN   LEU   TYR   MET   VAL   MET   GLU   TYR   VAL   ALA  
GLY   GLY   GLU   MET   PHE   SER   HIS   LEU   ARG   ARG  
ILE   GLY   ARG   PHE   GLU   PRO   HIS   ALA   ARG   PHE  
TYR   ALA   ALA   GLN   ILE   VAL   LEU   THR   PHE   GLU  
TYR   LEU   HIS   SER   LEU   ASP   LEU   ILE   TYR   ARG  
ASP   LEU   LYS   PRO   GLU   ASN   LEU   LEU   ILE   ASP  
GLN   GLN   GLY   TYR   ILE   GLN   VAL   THR   ASP   PHE  
GLY   PHE   ALA   LYS   ARG   VAL   LYS   GLY   ARG   THR  
TRP   LEU   CYSH  GLY   THR   PRO   GLU   TYR   LEU   ALA  
PRO   GLU   ILE   ILE   LEU   SER   LYS   GLY   TYR   ASN  
LYS   ALA   VAL   ASP   TRP   TRP   ALA   LEU   GLY   VAL  
LEU   ILE   TYR   GLU   MET   ALA   ALA   GLY   TYR   PRO  
PRO   PHE   PHE   ALA   ASP   GLN   PRO   ILE   GLN   ILE  
TYR   GLU   LYS   ILE   VAL   SER   GLY   LYS   VAL   ARG  
PHE   PRO   SER   HIS   PHE   SER   SER   ASP   LEU   LYS  
ASP   LEU   LEU   ARG   ASN   LEU   LEU   GLN   VAL   ASP  
LEU   THR   LYS   ARG   PHE   GLY   ASN   LEU   LYS   ASN  
GLY   VAL   ASN   ASP   ILE   LYS   ASN   HIS   LYS   TRP  
PHE   ALA   THR   THR   ASP   TRP   ILE   ALA   ILE   TYR  
GLN   ARG   LYS   VAL   GLU   ALA   PRO   PHE   ILE   PRO  
LYS   PHE   LYS   GLY   PRO   GLY   ASP   THR   SER   ASN  
PHE   ASP   ASP   TYR   GLU   GLU   GLU   GLU   ILE   ARG  
VAL   ILE   ASN   GLU   LYS   CYSH  GLY   LYS   GLU   PHE  
THR   GLU   PHET                                           
                                                           
                                                           
                                                           
                                                           
                                                           
                                                           
                                                           
                                                           
                                                           
                                                           
                                                           
                                                           
                                                           
                                                           
                                                           
                                                           
                                                           
                                                           
                                                           
                                                           
                                                           
                                                           
                                                           
                                                           
                                                           
                                                           
                                                           
                                                           
                                                           
                                                           
                                                           
                                                           
           

